### ISSUE TITLE
Is this really contributing to open source?

### ISSUE THREAD

**Issue by scitronboy** [amohata007/Hacktoberfest#104]
@amohata007 

Adding your name to a list is not really contributing to open source, in my opinion. What if you made it so that contributors have to make a little javascript widget/something like that in order to have their PRs accepted?

**Comment by amohata007** [comment]
good idea @scitronboy ..but the fact is there are many beginners who even don't know how to create their first pr ...so for them its an initialisation..

**Comment by scitronboy** [comment]
Okay. I think I might make a PR and add note to the README that encourages people to learn a language and make a code PR in a different repo along with this, because I do agree with you about this is a good first PR; however it seems like there are quite a few "first PR" repos created for Hacktoberfest and I think it needs to be clear that the goal of Hacktoberfest is to contribute to open source, _not_ race to make the most quick PRs.

Closing this now.
