### ISSUE TITLE
Change some text

### ISSUE THREAD

**Issue by amohata007** [amohata007/Hacktoberfest#2]

**Comment by hiteshpr** [comment]
I want to work on this. Can you add more description?

**Comment by fineanmol** [comment]
Just Check this Repo Also of Hacktober Fest to win T-shirt ..        [Repo Hacktoberfest2k18](https://github.com/fineanmol/Hacktoberfest2k18)

**Comment by amohata007** [comment]
https://github.com/amohata007/Hacktoberfest
contribute here....@hiteshpr
